### ISSUE TITLE
TLS/SSL brokes grocy website's 

### ISSUE THREAD

**Issue by lucki1000** [grocy/grocy-docker#102]
Hi,

I've used docker-compose to install grocy and used Let's Encrypt for SSL of my Apache2 reverse-proxy, but every time I will access grocy with https the Website is not correctly displayed, in the web source code stands any link to my domain with http and not with https, and thats the reason why my browser blocking this connections.

Source of grocy.domain.de-le-ssl.conf:
```
<IfModule mod_ssl.c>
<VirtualHost *:443> 
    ProxyPreserveHost On
    ProxyRequests Off
    ServerName grocy.domain.de
    ProxyPass / http://0.0.0.0:8443/
    ProxyPassReverse / http://0.0.0.0:8443/

SSLCertificateFile /etc/letsencrypt/live/grocy.domain.de/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/grocy.domain.de/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```
Source of docker-compose.yml:
```
version: '2.4'

services:

  nginx:
    image: "grocy/nginx:v2.7.1-4"
    build:
      args:
        GROCY_VERSION: v2.7.1
      context: .
      dockerfile: Dockerfile-grocy-nginx
    depends_on:
      - grocy
    ports:
      - '127.0.0.1:8443:8080'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx
    container_name: nginx

  grocy:
    image: "grocy/grocy:v2.7.1-4"
    restart: always
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/php7
      - app-db:/opt/grocy-data/
    env_file:
      - grocy.env
    container_name: grocy

volumes:
  app-db:
```
Source of grocy.env:
```
# Grocy Environment Variables

# These environment variables affect PHP and the grocy application
# For a full list of grocy settings, see config-dist.php in the main grocy repo:
#
#       https://github.com/grocy/grocy/blob/master/config-dist.php
#
# Grocy application settings must be prefixed with 'GROCY_'.
#
# For example, if we'd like to configure grocy to use Euros (EUR):
#
#       Setting('CURRENCY', 'USD');
#
# Then we would set GROCY_CURRENCY='EUR'. 


## User-supplied Variables

# These are environment variables that may be supplied by the user
# No values are supplied for these as part of this distribution

# When you're ready to deploy grocy in production, set GROCY_MODE=production
# to enable user authentication
GROCY_MODE


## Distribution-supplied Variables

# These are 'sensible defaults' provided as part of the grocy-docker
# distribution.

# GROCY_CULTURE configures localization of the grocy application
# Supported locales: https://github.com/grocy/grocy/tree/master/localization
GROCY_CULTURE=de
GROCY_CURRENCY='EUR'

# PHP Environment variables
MAX_UPLOAD=50M
PHP_MAX_FILE_UPLOAD=200
PHP_MAX_POST=100M
PHP_MEMORY_LIMIT=512M
```
I hope anyone can help me.
