### ISSUE TITLE
404 When Uploading Product Images - Behind HTTPS Reverse Proxy

### ISSUE THREAD

**Issue by thechickenmoo** [grocy/grocy-docker#11]
I've got a Jwilder Nginx Proxy Docker Container Running that handles the HTTPS Reverse Proxying. 

I've got other various containers running as well succesfully and had no problems getting Grocy to run. 

However i've been trying to upload product images and had some troubles. Oddly enough I was able to get 1 image to load no problem I thought initially it was pixel size or perhaps the file size itself, but I haven't been able to get any others to upload. 

I checked the logs on the proxy and here is what I'm seeing: 

```
 nginx.1    | grocy.thechickenmoo.com XXX.XX.X.X - - [02/Mar/2019:06:21:12 +0000] "GET /node_modules/moment/locale/x.js?v=1.24.1 HTTP/2.0" 404 888 "https://grocy.thechickenmoo.com/product/5"
 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"

 nginx.1    | grocy.thechickenmoo.com XXX.XX.X.X - - [02/Mar/2019:06:21:12 +0000] "GET /api/file/productpictures?file_name=j3f91l0ybbnlp95067xynabc123.jpg HTTP/2.0" 404 50 "https://grocy.the
chickenmoo.com/product/5" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"

```
So I get a 404 on the module and then a 404 on the image since it didn't actually get uploaded. 
The logs on the grocy server are: 

```
172.24.0.14 -  02/Mar/2019:06:25:10 +0000 "POST /index.php" 200
172.24.0.14 -  02/Mar/2019:06:25:10 +0000 "GET /index.php" 200
172.24.0.14 -  02/Mar/2019:06:25:10 +0000 "GET /index.php" 200
172.24.0.14 -  02/Mar/2019:06:25:16 +0000 "GET /index.php" 200
172.24.0.14 -  02/Mar/2019:06:25:16 +0000 "GET /index.php" 200
172.24.0.14 -  02/Mar/2019:06:25:16 +0000 "GET /index.php" 404
172.24.0.14 -  02/Mar/2019:06:25:16 +0000 "GET /index.php" 404
172.24.0.14 -  02/Mar/2019:06:25:16 +0000 "POST /index.php" 200
172.24.0.14 -  02/Mar/2019:06:25:16 +0000 "GET /index.php" 200
172.24.0.14 -  02/Mar/2019:06:25:16 +0000 "GET /index.php" 200
```

My Docker Compose: 
```
version: '2'

services:
  grocy-nginx:
    image: grocy/grocy-docker:nginx
    build:
      context: .
      dockerfile: Dockerfile-grocy-nginx
    depends_on:
      - grocy
    expose:
      - '80'
      - '443'
    environment:
      - VIRTUAL_HOST=grocy.thechickenmoo.com
      - LETSENCRYPT_HOST=grocy.thechickenmoo.com
      - LETSENCRYPT_EMAIL=XXXXXXXXX@XXXXXX.XXX
    volumes_from:
      - grocy
    container_name: grocy-nginx

  grocy:
    image: grocy/grocy-docker:grocy
    build:
      context: .
      dockerfile: Dockerfile-grocy
    expose:
      - 9000
    volumes:
      - database:/www
    environment:
      PHP_MEMORY_LIMIT:    512M
      MAX_UPLOAD:          50M
      PHP_MAX_FILE_UPLOAD: 200
      PHP_MAX_POST:        100M
      GROCY_CULTURE: en
    container_name: grocy
volumes:
  database:
networks:
   default:
     external:
       name: nginx-proxy
```
Am I missing something stupid? I keep trying but I'm going in circles so I figured I'd ask in the hopes of somebody being able to point me in the right direction. 

I made sure that the proxy (It's nginx based) has the settings below:
client_max_body_size 200m;
client_body_buffer_size 200m;

The error I get on the page is:

![capture1](https://user-images.githubusercontent.com/3395535/53678361-e3f60400-3c72-11e9-9c9e-1e4082307f07.PNG)
![capture](https://user-images.githubusercontent.com/3395535/53678366-e9ebe500-3c72-11e9-8c04-a91bce1de540.PNG)

What can I do to fix this? I want to use this in my home but I know my wife won't touch it unless I get it up and running without errors :D
