### ISSUE TITLE
grocy/grocy-docker or linuxserver/grocy

### ISSUE THREAD

**Issue by mx2k** [grocy/grocy-docker#200]
Hello,
I am using the linuxserver/grocy docker package, but this seems not the official Grocy docker image. I wanted to switch to official repository but am running into issues deploying my stack.

It says in the readme run docker-compose with the downloaded docker-compose.yaml file. Since I am using Portainer to deploy my stacks on my Docker running on a NAS there is no SSH access for CLI commands to deploy things.

Do i need to do more than copy the contents from the docker-compose.yaml to my Portainer stack editor and click on deploy?  This doesn't work for some reason. (but it works with linuxserver.io stack)

Currently, I start grocy this way. I do not understand how to adapt my docker-compose to the one provide here in the official repository.

```
version: "3"

services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - GROCY_CULTURE=de
      - MAX_UPLOAD=50M
      - PHP_MAX_FILE_UPLOAD=200
      - PHP_MAX_POST=100M
      - PHP_MEMORY_LIMIT=512M
    volumes:
      - /volume1/docker/grocy-data:/config
    ports:
      - 8080:80
    restart: unless-stopped

```
