### ISSUE TITLE
Boolean values are not allowed in environmental variables

### ISSUE THREAD

**Issue by lukasleitsch** [grocy/grocy-docker#22]
I want to disable some features. As you described this is possible with setting the environment variables. This is  the relevant part from my docker-compose.yml file:

```
    environment:
      PHP_MEMORY_LIMIT: 512M
      MAX_UPLOAD: 50M
      PHP_MAX_FILE_UPLOAD: 200
      PHP_MAX_POST: 100M
      GROCY_CULTURE: de
      GROCY_FEATURE_FLAG_RECIPES: false
      GROCY_FEATURE_FLAG_TASKS: false
```

This config doesn't work and Docker Compose throws the following error:

```services.grocy.environment.GROCY_FEATURE_FLAG_RECIPES contains false, which is an invalid type, it should be a string, number, or a null
```

The variables `GROCY_FEATURE_FLAG_RECIPES` and `GROCY_FEATURE_FLAG_TASKS` can't be a boolean and must be a string. If I set the variables with `'true'` docker composer start without the error. But the true string won't be parsed in the app correctly.

Do you have an idea to disable features with the docker environment variables?
