### ISSUE TITLE
Frontend issues with grocy >= 4.0.1

### ISSUE THREAD

**Issue by tmm360** [grocy/grocy-docker#223]
I'm using Grocy with docker compose. With version 4.0.0 I've no problems, with versions 4.0.1 and 4.0.2 when I try to access to `http://<myserverip>:8081/stockoverview` I get only a black page with a barcode in the middle, and trying to access in private mode I get an infinite 302 redirect to `http://<myserverip>:8081/login`. 

My docker compose file:

```
version: '3.8'

services:

  frontend:
    image: "grocy/frontend:v4.0.2"
    depends_on:
      - backend
    ports:
      - '8081:8080'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx
    restart: always

  backend:
    image: "grocy/backend:v4.0.2"
    environment:
      - GROCY_MODE=production
      - GROCY_CULTURE=it
      - MAX_UPLOAD=50M
      - PHP_MAX_FILE_UPLOAD=200
      - PHP_MAX_POST=100M
      - PHP_MEMORY_LIMIT=512M
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/php8
      - app-db:/var/www/data
    restart: always

volumes:
  app-db:
```

I've tested with both Brave and Firefox.
