### ISSUE TITLE
Allow changing the name of the backend container.

### ISSUE THREAD

**Issue by max-tet** [grocy/grocy-docker#230]
I am trying this docker-compose:
```yml
version: '2.4'

services:

  grocy-frontend:
    image: "grocy/frontend:v4.0.3"
    container_name: grocy-frontend
    depends_on:
      - grocy-backend
    ports:
      - '8080:8080'

  grocy-backend:
    image: "grocy/backend:v4.0.3"
    container_name: grocy-backend
    volumes:
      - ./db:/var/www/data/db
      - ./storage:/var/www/data/storage
    environment:
      - GROCY_DISABLE_AUTH=true
```
Note that I renamed the containers. This makes sense if you want to host multiple apps and avoid ambiguity.

However, when running, this error is logged.
```
host not found in upstream "backend" in /etc/nginx/common.conf:12
```

Seems like this is caused by the backend container name being hardcoded as `backend` [here](https://github.com/grocy/grocy-docker/blob/main/static/frontend/common.conf#L12C25-L12C25).

Is there a way to configure this value without rebuilding the image? An environment variable would be the best choice.
