### ISSUE TITLE
Empty / incomplete www directory in running container

### ISSUE THREAD

**Issue by nlighteneddesign** [grocy/grocy-docker#29]
I am using just the standalone docker container since I have a separate nginx container I use for everything. When I spin it up the log says the following:
```
[04-Mar-2020 01:35:53] NOTICE: fpm is running, pid 1,
[04-Mar-2020 01:35:53] NOTICE: ready to handle connections,
```

However if I try to connect to the exposed port it doesn't work.

Logging in and trying to curl the port gives the following:
```
/www/public # curl localhost:9000
curl: (56) Recv failure: Connection reset by peer
```

It does show that it's listening on 9000 though

```
netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.11:43733        0.0.0.0:*               LISTEN      -
tcp        0      0 :::9000                 :::*                    LISTEN      1/php-fpm.conf)
```

Here is my docker-compose:
```
  grocy:
    build:
      context: ./containers/grocy
    container_name: grocy
    ports:
      - 8234:9000
    volumes:
      - /srv/docker/grocy:/www
    environment:
      - PHP_MEMORY_LIMIT=512M
      - MAX_UPLOAD=50M
      - PHP_MAX_FILE_UPLOAD=200
      - PHP_MAX_POST=100M
      - GROCY_CULTURE=en
```

I also tried using the image directly first.
