### ISSUE TITLE
Subdomain => 404 (when running with Docker)

### ISSUE THREAD

**Issue by tbrunain** [grocy/grocy-docker#3]
Hello,

I'm trying to set up grocy (docker-compose way) with Traefik to handle a subdomain (grocy.xxxx.xx) .
I can start grocy but I get a 404 on all the resources , the main html file is fine though and I see an ugly html , links are working and login as well.

I'm sure I missed a stupid config somewhere but can't figure out where :x

**Comment by talmai** [comment]
Closing this issue as it relates more to the conflict between traefik and nginx (both assuming roles of proxy), than to grocy-docker.

**Comment by Braintelligence** [comment]
@tbrunain Did you find a solution?

**Comment by jakob42** [comment]
@tbrunain I deployed grocy yesterday with traefik and had a similar problem. I don't think it was traefik related though. I had changed the volume to a directory and it didn't get populated (even though access rights were fine.) I checked in a shell (`docker exec -it grocy /bin/sh`) in the container if there were files in `/www`. Since it only had an empty public directory, I thought the problem with the 404 was related. I changed it back to the default volume the compose file used and it worked. 

Here is my docker-compose, if it helps. I have traefik setup to use docker labels for settings.

```
version: '2'

services:
  grocy-nginx:
    image: grocy/grocy-docker:nginx
    depends_on:
      - grocy
    volumes_from:
      - grocy
    container_name: grocy-nginx
    networks:
      - web
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:grocy.my.domain.de"
      - "traefik.port=80"
      - "traefik.protocol=http"

  grocy:
    image: grocy/grocy-docker:grocy
    expose:
      - 9000
    volumes:
      - database:/www
    environment:
      PHP_MEMORY_LIMIT:    512M
      MAX_UPLOAD:          50M
      PHP_MAX_FILE_UPLOAD: 200
      PHP_MAX_POST:        100M
    container_name: grocy
    networks:
      - web

networks:
  web:
    external:
      name: web
```
