### ISSUE TITLE
Been looking forward to this app, will there be an unopinionated docker-compose without a webserver?

### ISSUE THREAD

**Issue by Leopere** [grocy/grocy-docker#92]
I typically can figure it out on my own and may eventually do it but there's a variety of reverse proxies many of which maintain their own TLS certificates Nginx not being one of them.  Would it be reasonable to ask for an example where there isn't a webserver included in case someone like me wanted to use Traefik on the front end or someone else who might want to use Caddy server?  You wouldn't even really need to maintain much more with this route of publishing an example without a webserver front end.

**Comment by jayaddison** [comment]
Hi @Leopere, thanks for getting in touch; it's reasonable to ask questions.  We're a volunteer team doing this in our own time, and will do our best to help.  Contributions are also welcome.

Could you describe what the issue you're experiencing is, and what would resolve it for you?

If it remains unclear what action is required to solve the issue, it may be closed.

**Comment by Leopere** [comment]
Hey, no worries! I have no expectations just a suggestion for potentially a lower maintenance docker-compose.yml example wherein the Grocy community doesn't have to maintain more versions of the microservices cluster.

Essentially there are several offerings available for front end internet-facing Reverse Proxies.  With this in mind, it may make sense to show a bare Grocy example where you publish it with your mileage may vary as a disclaimer.  Just tell them what port we decide to expose Grocy on by default and leave it at that.

*Pending example inbound*

**Comment by kses** [comment]
I thought I should add there is also a more barebones docker container that is maintained by linuxserver.io

Adding my docker compose file below.

I would also think that the simplest way to get a server style instance running if you do not have any linux experience is to run home assistant on a RPi and install grocy as an add-on.

```
version: '3'
services:
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Europe/Stockholm"
    volumes:
      - /home/<username>/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
```
